# hardening.yml
- name: Security Hardening
  hosts: webservers
  tasks:
    - name: Ensure latest updates
      yum:
        name: '*'
        state: latest
- name: Hardening 
  hosts: webservers 
  tasks: 
    - name: ensure latest update 
        yum:
          name: '*'
          state: latest
